plugin: aws_ec2

#aws_access_key: ACCESS_KEY
#aws_secret_key: aws_secret

regions:
 - us-east-1

filters:
  instance-state-name: running

keyed_groups:
  - key: tags.Name
    prefix: ""
    separator: ""

hostnames:
 - private-ip-address

compose:
  ansible_host: private-ip-address
